"""add conflict_resolutions table

Revision ID: 394815f1ac84
Revises: 3939ba0e0346
Create Date: 2026-03-05 20:50:33.017421
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '394815f1ac84'
down_revision: Union[str, None] = '3939ba0e0346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflict_resolutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('strategies', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_resolutions_created_at'), 'conflict_resolutions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conflict_resolutions_ticker'), 'conflict_resolutions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conflict_resolutions_ticker'), table_name='conflict_resolutions')
    op.drop_index(op.f('ix_conflict_resolutions_created_at'), table_name='conflict_resolutions')
    op.drop_table('conflict_resolutions')
    # ### end Alembic commands ###
