"""
News API Endpoints
==================
Serves cached news, sentiment, company info, and bull/bear thesis.
"""

import logging
from fastapi import APIRouter, Query
from app.services.news_service import news_service, get_company_description

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/news")
async def get_news(
    ticker: str | None = Query(None, description="Filter by ticker symbol"),
    limit: int = Query(20, ge=1, le=100),
    hours: int = Query(24, ge=1, le=168),
):
    """Get cached news articles, optionally filtered by ticker."""
    articles = await news_service.get_cached_news(
        ticker=ticker, limit=limit, hours=hours
    )
    return {"articles": articles, "count": len(articles)}


@router.get("/news/ticker/{ticker}")
async def get_ticker_news(ticker: str):
    """Get news, sentiment, and company info for a specific ticker."""
    ticker = ticker.upper().strip()

    # Fetch all three in parallel
    import asyncio

    headlines_task = news_service.get_ticker_headlines(ticker, limit=10)
    sentiment_task = news_service.get_news_sentiment(ticker)
    company_task = get_company_description(ticker)

    headlines, sentiment, company = await asyncio.gather(
        headlines_task, sentiment_task, company_task,
        return_exceptions=True,
    )

    # Handle any individual failures gracefully
    if isinstance(headlines, Exception):
        headlines = []
    if isinstance(sentiment, Exception):
        sentiment = {"score": 0.0, "label": "Neutral", "article_count": 0}
    if isinstance(company, Exception):
        company = {
            "name": ticker,
            "sector": None,
            "industry": None,
            "market_cap": None,
            "description": None,
            "high_52w": None,
            "low_52w": None,
        }

    return {
        "ticker": ticker,
        "company": company,
        "sentiment": sentiment,
        "headlines": headlines,
    }


@router.get("/news/ticker/{ticker}/thesis")
async def get_ticker_thesis(ticker: str):
    """
    Get a cached bull/bear thesis for a ticker.
    Generated by Gemini, cached until explicitly refreshed.
    """
    ticker = ticker.upper().strip()

    # Check cache first
    try:
        from app.database import async_session
        from app.models.henry_cache import HenryCache
        from sqlalchemy import select

        async with async_session() as db:
            result = await db.execute(
                select(HenryCache).where(
                    HenryCache.cache_key == f"thesis:{ticker}",
                    HenryCache.cache_type == "bull_bear_thesis",
                    HenryCache.is_stale == False,
                )
            )
            cached = result.scalar_one_or_none()
            if cached:
                import json
                return {
                    "ticker": ticker,
                    "thesis": json.loads(cached.content) if isinstance(cached.content, str) else cached.content,
                    "generated_at": cached.generated_at.isoformat() if cached.generated_at else None,
                    "cached": True,
                }
    except Exception:
        pass

    return {"ticker": ticker, "thesis": None, "cached": False}


@router.post("/news/ticker/{ticker}/thesis")
async def generate_ticker_thesis(ticker: str):
    """
    Generate a bull/bear thesis for a ticker using Gemini.
    Caches the result for future lookups.
    """
    ticker = ticker.upper().strip()

    try:
        # Get context: company info + recent headlines
        import asyncio
        company = await get_company_description(ticker)
        headlines = await news_service.get_ticker_headlines(ticker, limit=5)

        company_ctx = ""
        if company and company.get("name"):
            company_ctx = f"Company: {company['name']}"
            if company.get("sector"):
                company_ctx += f" | Sector: {company['sector']}"
            if company.get("industry"):
                company_ctx += f" | Industry: {company['industry']}"
            if company.get("market_cap"):
                company_ctx += f" | Market Cap: ${company['market_cap']:,.0f}"
            if company.get("description"):
                company_ctx += f"\nBusiness: {company['description']}"
            if company.get("high_52w") and company.get("low_52w"):
                company_ctx += f"\n52-week range: ${company['low_52w']:.2f} - ${company['high_52w']:.2f}"

        news_ctx = ""
        if headlines:
            news_lines = [f"  - {h.get('headline', '')}" for h in headlines[:5]]
            news_ctx = "Recent headlines:\n" + "\n".join(news_lines)

        prompt = f"""Generate a concise bull/bear thesis for {ticker}.

{company_ctx}

{news_ctx}

Return a JSON object with this exact structure:
{{
  "bull_case": "2-3 sentence bull thesis — why this stock could go up significantly",
  "bear_case": "2-3 sentence bear thesis — the key risks and why it could go down",
  "key_catalysts": ["catalyst 1", "catalyst 2", "catalyst 3"],
  "risk_factors": ["risk 1", "risk 2", "risk 3"],
  "sentiment_summary": "One sentence: what's the overall market sentiment right now?"
}}

Be specific to {ticker} — reference actual business drivers, not generic statements. Keep each thesis under 80 words."""

        from app.services.ai_provider import call_ai
        raw = await call_ai(
            system="You are a financial analyst. Return ONLY valid JSON, no markdown, no code blocks.",
            prompt=prompt,
            function_name="watchlist_summary",
            max_tokens=600,
        )

        # Parse JSON
        import json
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
        thesis_data = json.loads(cleaned)

        # Cache it
        try:
            from app.database import async_session
            from app.models.henry_cache import HenryCache
            from sqlalchemy import select
            import uuid
            from datetime import datetime

            async with async_session() as db:
                # Delete old cache
                result = await db.execute(
                    select(HenryCache).where(
                        HenryCache.cache_key == f"thesis:{ticker}",
                        HenryCache.cache_type == "bull_bear_thesis",
                    )
                )
                old = result.scalar_one_or_none()
                if old:
                    await db.delete(old)
                    await db.flush()

                cache_entry = HenryCache(
                    id=str(uuid.uuid4()),
                    cache_key=f"thesis:{ticker}",
                    cache_type="bull_bear_thesis",
                    content=json.dumps(thesis_data),
                    ticker=ticker,
                    is_stale=False,
                    generated_at=datetime.utcnow(),
                )
                db.add(cache_entry)
                await db.commit()
        except Exception as e:
            logger.warning(f"Failed to cache thesis for {ticker}: {e}")

        # Also save to Henry's memory for reference
        try:
            from app.services.ai_service import save_memory
            await save_memory(
                content=f"Bull thesis on {ticker}: {thesis_data.get('bull_case', '')}. Bear thesis: {thesis_data.get('bear_case', '')}",
                memory_type="observation",
                ticker=ticker,
                importance=6,
                source="thesis_generator",
            )
        except Exception:
            pass

        return {
            "ticker": ticker,
            "thesis": thesis_data,
            "generated_at": datetime.utcnow().isoformat() if 'datetime' in dir() else None,
            "cached": False,
        }

    except json.JSONDecodeError:
        return {"ticker": ticker, "thesis": None, "error": "Failed to parse AI response"}
    except Exception as e:
        logger.error(f"Failed to generate thesis for {ticker}: {e}")
        return {"ticker": ticker, "thesis": None, "error": str(e)}
